#/etc/netplan/99-config.yaml
#netplan configuration file taita VM: netsec-public, netsec
network:
        version: 2
        renderer: networkd
        ethernets:
                #internet via netsec-public
                ens18:
                        #dhcp route adds default unless dhcp4-overrides, use-routes: false
                        dhcp4: true
                        dhcp4-overrides:
                                use-dns: false
                        routes:
                              - to: default
                                via: 192.168.15.1 #customize this with your own internet router IP address
                        nameservers:
                                addresses: [192.168.15.1, 8.8.8.8, 1.1.1.1]  #customize this with your own internet router IP address (leave 8.8.8.8 and 1.1.1.1)
                                search: [invalid] #leave this as is
                #netsec
                ens19:
                        #dhcp route adds default unless dhcp4-overrides, use-routes: false
                        dhcp4: true
                        dhcp4-overrides:
                                use-routes: false
                        nameservers:
                                addresses: [172.16.0.10]
                                search: [netsec.isi.jhu.edu]  
